### ISSUE TITLE
Can't parse numbers

### ISSUE THREAD

**Issue by sverrirs** [scf4/callbaxx#11]
I have all these numbers stuck in strings and no parse methods. 
Plz add parse methods... I urgently need it for production code!

Example of numbers I must be able to parse:
```
"3"
"5.1"
"61"
"5.11"
"14" <== this is very important
```

**Comment by scf4** [comment]
Thanks for your interest in the project. As Callbaxx is new, we don't have such a function just yet, but we'll be sure to have a much more performant Callbaxx version of every native function necessary for modern web applications in our 1.0.0 release.

JavaScript actually has a synchronous `parseInt` function, but that will probably block the event loop or whatever, especially since you're running in production and probably have a lot of legacy promise and async/await code slowing things down. Nevertheless, it _might_ work, depending on how much performance you need.

My hands are tied at the moment, but I'd welcome a PR for such a function, from you or anyone else. 

Thanks again
Scott

**Comment by AlecsisDuarte** [comment]
Hi I would like to work on this one, if that's ok @scf4

**Comment by AlecsisDuarte** [comment]
I just have some questions about the request.
Will the numbers to be parse be in an array of strings or just a string?

**Comment by scf4** [comment]
@AlecsisDuarte great, thanks!

I the function should be called parseNumber which takes a string and returns a number using `parseFloat`.

Then if you want to parse an _array_ of strings you can just use callbaxx.map. I'm about to push a commit which lets you use a callback function with callbaxx.map... I can't believe I left that out!
```

**Comment by sverrirs** [comment]
This is great! Please pay special attention to the string-locked number fourteen, here is a sample I copied directly from one of my PROD environments

```
14
```

Thought you might want to use real data from production.

**Comment by scf4** [comment]
That should be on the user side. To map over an array of strings and turn them into numbers you should be able to just do this:

```js
callbaxx.map(["3", "5.1", "61", "5.11", "14"], callbaxx.parseNumber, function (err, res) {
  console.log(res);
}, true);

// Output: [3, 5.1, 61, 5.11, 14]

```
Note the `true` arg for `mapFnRequiresCallback` (See [lib/map.js](https://github.com/scf4/callbaxx/blob/master/lib/map.js) for more info)

**Comment by AlecsisDuarte** [comment]
#16 Here is my PR
Hope it fulfills the issue, any correction needed I'll be glad to fix it

**Comment by scf4** [comment]
Amazing work. Thank you both for contributing to the project!
