### ISSUE TITLE
RFC: Improving callbaxx code

### ISSUE THREAD

**Issue by scf4** [scf4/callbaxx#5]
For the initial release I've written each function by hand, but things would be a **lot more stable** and more **D.R.Y.** if we depend on other packages for the logic of the functions.
 
At the moment this package has **0 dependencies**, which doesn't feel right at all. Would you trust a package with 0 dependencies? I know I wouldn't. 

I'm going to go ahead and `npm install lodash` just to give the repo a bit more credibility.

Any other thoughts on improving the code?

**Comment by malydok** [comment]
Any respectful library needs to have `left-pad` as a dependency.
We could also callbaxxify the function while we're at it, it's barely usable otherwise.

**Comment by efokschaner** [comment]
Something I'm seeing a lot of in this library is the pattern of taking a synchronous function and then wrapping it in order to return its results via a callback. I think the code would be greatly improved if we factored this out in to a utility called `callbackify`. Something along the following lines:
```
function callbackifyCombinator(f) {
  return function () {
    var cbIndex = arguments.length - 1;
    var cb = arguments[cbIndex];
    try {
      cb(null, f.apply(null, Array.prototype.slice.call(arguments, 0, cbIndex)));
    } catch(e) {
      cb(e, null);
    }
  };
}

// Wraps a function with a callbaxx(TM) style interface
// callbackify calls its callback with the wrapped function if it succeeds
var callbackify = callbackifyCombinator(callbackifyCombinator);

// Used as follows
callbackify(Math.max, function(err, cbMax) {
  cbMax(1,2,3,4,console.log.bind(console));
})
// Outputs "null 4"
```

This can then be kept in a separate package within this repo and we can manage the monorepo using a combination of Lerna (https://github.com/lerna/lerna) and Yarn Workpsaces (https://yarnpkg.com/lang/en/docs/workspaces/)
